<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>sphere_sim</name>
  <version>0.0.1</version>
  <description>Oscillating sphere simulation in Gazebo Harmonic with ROS 2</description>
  <maintainer email="user@todo.todo">developer</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>ros_gz_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>